export const IPC = {
  // Renderer -> Main (invoke/handle)
  TERMINAL_SPAWN: 'terminal:spawn',
  TERMINAL_WRITE: 'terminal:write',
  TERMINAL_RESIZE: 'terminal:resize',
  TERMINAL_KILL: 'terminal:kill',
  TERMINAL_GET_SESSION_ID: 'terminal:getSessionId',
  TERMINAL_RESUME_IN_NATIVE: 'terminal:resumeInNative', // args: terminalId, claudeFlags?
  TERMINAL_SYNC_ORDER: 'terminal:syncOrder',
  TERMINAL_RESPAWN: 'terminal:respawn',
  TERMINAL_LIST_SESSIONS: 'terminal:listSessions',
  TERMINAL_POP_CLOSED_SESSION: 'terminal:popClosedSession',
  // Shell panel PTY (embedded non-Claude shell per terminal)
  SHELL_SPAWN: 'shell:spawn',
  SHELL_WRITE: 'shell:write',
  SHELL_RESIZE: 'shell:resize',
  SHELL_KILL: 'shell:kill',
  SHELL_DATA: 'shell:data',       // Main -> Renderer
  SHELL_EXIT: 'shell:exit',       // Main -> Renderer
  SHELL_EVENT: 'shell:event',     // Main -> Renderer
  SHELL_EVENT_DISMISS: 'shell:eventDismiss', // Renderer -> Main (remove from pending file)
  SHELL_RUN_COMMAND: 'shell:runCommand', // Main -> Renderer (open shell panel + run command)
  SHELL_CLEAR: 'shell:clear',           // Main -> Renderer (clear a shell panel's terminal + buffer)

  DOCK_GET_INFO: 'dock:getInfo',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  SETTINGS_SET_PROJECT: 'settings:setProject',
  SETTINGS_GET_ORIGINS: 'settings:getOrigins',
  SETTINGS_RESET_PROJECT_KEY: 'settings:resetProjectKey',
  APP_NEW_DOCK: 'app:newDock',
  APP_PICK_DIRECTORY: 'app:pickDirectory',
  APP_GET_RECENT_PATHS: 'app:getRecentPaths',
  APP_REMOVE_RECENT_PATH: 'app:removeRecentPath',
  APP_OPEN_DOCK_PATH: 'app:openDockPath',
  APP_FOCUS_DOCK_PATH: 'app:focusDockPath',
  WIN_MINIMIZE: 'win:minimize',
  WIN_MAXIMIZE: 'win:maximize',
  WIN_CLOSE: 'win:close',
  APP_CLOSE_ALL: 'app:closeAll',
  APP_OPEN_EXTERNAL: 'app:openExternal',
  APP_RELAUNCH: 'app:relaunch',
  APP_OPEN_IN_EXPLORER: 'app:openInExplorer',
  UPDATER_CHECK: 'updater:check',
  UPDATER_DOWNLOAD: 'updater:download',
  UPDATER_INSTALL: 'updater:install',
  UPDATER_SAVE_PENDING_PROJECT: 'updater:savePendingProject',
  UPDATER_IS_LOCKED: 'updater:isLocked',
  UPDATER_HAS_ACTIVE_TERMINALS: 'updater:hasActiveTerminals',
  GIT_CHECK: 'git:check',
  GIT_INSTALL: 'git:install',
  GIT_CLONE: 'git:clone',
  GIT_GET_BRANCH: 'git:getBranch',

  // Local LLM (app-level service)
  LLM_STATUS: 'llm:status',
  LLM_DOWNLOAD: 'llm:download',
  LLM_DOWNLOAD_PROGRESS: 'llm:downloadProgress',
  CLAUDE_CHECK_INSTALL: 'claude:checkInstall',
  CLAUDE_INSTALL: 'claude:install',
  CLAUDE_VERSION: 'claude:version',
  CLAUDE_CHECK_PATH: 'claude:checkPath',
  CLAUDE_FIX_PATH: 'claude:fixPath',
  CONTEXT_MENU_CHECK: 'contextMenu:check',
  CONTEXT_MENU_REGISTER: 'contextMenu:register',
  CONTEXT_MENU_UNREGISTER: 'contextMenu:unregister',
  DOCK_RESTART: 'dock:restart',
  DOCK_SWITCH_PROJECT: 'dock:switchProject',
  LINKED_CHECK_MCP: 'linked:checkMcp',
  LINKED_INSTALL_MCP: 'linked:installMcp',
  LINKED_UNINSTALL_MCP: 'linked:uninstallMcp',
  LINKED_SET_ENABLED: 'linked:setEnabled',
  LINKED_SET_MESSAGING: 'linked:setMessaging',
  PLUGIN_GET_LIST: 'plugin:getList',
  PLUGIN_GET_STATES: 'plugin:getStates',
  PLUGIN_SET_ENABLED: 'plugin:setEnabled',
  PLUGIN_GET_SETTING: 'plugin:getSetting',
  PLUGIN_SET_SETTING: 'plugin:setSetting',
  PLUGIN_IS_CONFIGURED: 'plugin:isConfigured',
  PLUGIN_MARK_CONFIGURED: 'plugin:markConfigured',
  PLUGIN_GET_TOOLBAR_ACTIONS: 'plugin:getToolbarActions',
  PLUGIN_GET_DIR: 'plugin:getDir',
  PLUGIN_OPEN_DIR: 'plugin:openDir',
  PLUGIN_RESET_TRUST: 'plugin:resetTrust',
  PLUGIN_GET_OVERRIDES: 'plugin:getOverrides',
  DEBUG_WRITE: 'debug:write',
  DEBUG_REPORT_CRASH: 'debug:reportCrash',
  DEBUG_OPEN_DEVTOOLS: 'debug:openDevTools',
  DEBUG_OPEN_LOGS: 'debug:openLogs',
  BUG_REPORT_SUBMIT: 'bugReport:submit',

  // Git Manager
  GIT_MGR_IS_REPO: 'gitMgr:isRepo',
  GIT_MGR_OPEN: 'gitMgr:open',
  GIT_MGR_OPEN_COMMIT: 'gitMgr:openCommit',
  GIT_MGR_GET_LOG: 'gitMgr:getLog',
  GIT_MGR_GET_COMMIT_COUNT: 'gitMgr:getCommitCount',
  GIT_MGR_GET_COMMIT_INDEX: 'gitMgr:getCommitIndex',
  GIT_MGR_GET_BRANCHES: 'gitMgr:getBranches',
  GIT_MGR_GET_STATUS: 'gitMgr:getStatus',
  GIT_MGR_GET_DIFF: 'gitMgr:getDiff',
  GIT_MGR_GET_COMMIT_DETAIL: 'gitMgr:getCommitDetail',
  GIT_MGR_STAGE: 'gitMgr:stage',
  GIT_MGR_UNSTAGE: 'gitMgr:unstage',
  GIT_MGR_COMMIT: 'gitMgr:commit',
  GIT_MGR_CHECKOUT_BRANCH: 'gitMgr:checkoutBranch',
  GIT_MGR_CREATE_BRANCH: 'gitMgr:createBranch',
  GIT_MGR_DELETE_BRANCH: 'gitMgr:deleteBranch',
  GIT_MGR_PULL: 'gitMgr:pull',
  GIT_MGR_PUSH: 'gitMgr:push',
  GIT_MGR_PUSH_FORCE_WITH_LEASE: 'gitMgr:pushForceWithLease',
  GIT_MGR_PUSH_WITH_TAGS: 'gitMgr:pushWithTags',
  GIT_MGR_PUSH_TAG: 'gitMgr:pushTag',
  GIT_MGR_CANCEL_PUSH: 'gitMgr:cancelPush',
  GIT_MGR_FETCH: 'gitMgr:fetch',
  GIT_MGR_STASH_LIST: 'gitMgr:stashList',
  GIT_MGR_STASH_SAVE: 'gitMgr:stashSave',
  GIT_MGR_STASH_APPLY: 'gitMgr:stashApply',
  GIT_MGR_STASH_POP: 'gitMgr:stashPop',
  GIT_MGR_STASH_DROP: 'gitMgr:stashDrop',
  GIT_MGR_GET_SUBMODULES: 'gitMgr:getSubmodules',
  GIT_MGR_GET_SUBMODULE_LIST: 'gitMgr:getSubmoduleList',
  GIT_MGR_REFRESH_SUBMODULE: 'gitMgr:refreshSubmodule',
  GIT_MGR_GENERATE_COMMIT_MSG: 'gitMgr:generateCommitMsg',
  GIT_MGR_RESET: 'gitMgr:reset',
  GIT_MGR_REVERT: 'gitMgr:revert',
  GIT_MGR_CHERRY_PICK: 'gitMgr:cherryPick',
  GIT_MGR_CREATE_TAG: 'gitMgr:createTag',
  GIT_MGR_DELETE_TAG: 'gitMgr:deleteTag',
  GIT_MGR_GET_TAGS: 'gitMgr:getTags',
  GIT_MGR_RENAME_BRANCH: 'gitMgr:renameBranch',
  GIT_MGR_DISCARD: 'gitMgr:discard',
  GIT_MGR_RESTORE_FILE_FROM_COMMIT: 'gitMgr:restoreFileFromCommit',
  GIT_MGR_DELETE_FILES: 'gitMgr:deleteFiles',
  GIT_MGR_SHOW_IN_FOLDER: 'gitMgr:showInFolder',
  GIT_MGR_APPLY_PATCH: 'gitMgr:applyPatch',
  GIT_MGR_GET_FILE_BLOB: 'gitMgr:getFileBlob',
  GIT_MGR_GET_COMMIT_FILE_TREE: 'gitMgr:getCommitFileTree',
  GIT_MGR_GET_FILE_AT_COMMIT: 'gitMgr:getFileAtCommit',
  GIT_MGR_GET_FILE_LOG: 'gitMgr:getFileLog',
  GIT_MGR_OPEN_FILE_HISTORY: 'gitMgr:openFileHistory',
  GIT_MGR_GREP_COMMIT: 'gitMgr:grepCommit',
  GIT_MGR_OPEN_BASH: 'gitMgr:openBash',
  GIT_MGR_ADD_SUBMODULE: 'gitMgr:addSubmodule',
  GIT_MGR_REGISTER_SUBMODULE: 'gitMgr:registerSubmodule',
  GIT_MGR_REMOVE_SUBMODULE: 'gitMgr:removeSubmodule',
  GIT_MGR_SYNC_SUBMODULES: 'gitMgr:syncSubmodules',
  GIT_MGR_UPDATE_SUBMODULES: 'gitMgr:updateSubmodules',
  GIT_MGR_PULL_REBASE_SUBMODULES: 'gitMgr:pullRebaseSubmodules',
  GIT_MGR_FORCE_REINIT_SUBMODULE: 'gitMgr:forceReinitSubmodule',
  GIT_MGR_CHECK_SUBMODULE_ACCESS: 'gitMgr:checkSubmoduleAccess',
  GIT_MGR_GET_REMOTES: 'gitMgr:getRemotes',
  GIT_MGR_ADD_REMOTE: 'gitMgr:addRemote',
  GIT_MGR_REMOVE_REMOTE: 'gitMgr:removeRemote',
  GIT_MGR_RENAME_REMOTE: 'gitMgr:renameRemote',
  GIT_MGR_SET_REMOTE_URL: 'gitMgr:setRemoteUrl',
  GIT_MGR_GET_MERGE_STATE: 'gitMgr:getMergeState',
  GIT_MGR_GET_CONFLICT_CONTENT: 'gitMgr:getConflictContent',
  GIT_MGR_RESOLVE_CONFLICT: 'gitMgr:resolveConflict',
  GIT_MGR_ABORT_MERGE: 'gitMgr:abortMerge',
  GIT_MGR_CONTINUE_MERGE: 'gitMgr:continueMerge',
  GIT_MGR_MERGE_BRANCH: 'gitMgr:mergeBranch',
  GIT_MGR_PULL_ADVANCED: 'gitMgr:pullAdvanced',
  GIT_MGR_FETCH_SIMPLE: 'gitMgr:fetchSimple',
  GIT_MGR_FETCH_ALL: 'gitMgr:fetchAll',
  GIT_MGR_FETCH_PRUNE_ALL: 'gitMgr:fetchPruneAll',
  GIT_MGR_GET_BEHIND_COUNT: 'gitMgr:getBehindCount',
  GIT_MGR_GET_SETTING: 'gitMgr:getSetting',
  GIT_MGR_REMOVE_LOCK_FILE: 'gitMgr:removeLockFile',
  GIT_MGR_GET_IDENTITY: 'gitMgr:getIdentity',
  GIT_MGR_SET_IDENTITY: 'gitMgr:setIdentity',
  GIT_MGR_SEARCH: 'gitMgr:search',
  GIT_MGR_GET_ACTIVE_TERMINALS: 'gitMgr:getActiveTerminals',
  GIT_MGR_SAVE_FILE: 'gitMgr:saveFile',
  GIT_MGR_RESOLVE_WITH_CLAUDE: 'gitMgr:resolveWithClaude',
  GIT_MGR_PREVIEW_GITIGNORE: 'gitMgr:previewGitignore',
  GIT_MGR_ADD_TO_GITIGNORE: 'gitMgr:addToGitignore',
  GIT_MGR_MIGRATE_TO_LFS: 'gitMgr:migrateToLfs',
  GIT_MGR_LIST_WORKTREES: 'gitMgr:listWorktrees',
  GIT_MGR_ADD_WORKTREE: 'gitMgr:addWorktree',
  GIT_MGR_REMOVE_WORKTREE: 'gitMgr:removeWorktree',
  GIT_MGR_RESOLVE_WORKTREE: 'gitMgr:resolveWorktree',

  // CI
  CI_CHECK_AVAILABLE: 'ci:checkAvailable',
  CI_GET_SETUP_STATUS: 'ci:getSetupStatus',
  CI_RUN_SETUP_ACTION: 'ci:runSetupAction',
  CI_GET_WORKFLOWS: 'ci:getWorkflows',
  CI_GET_WORKFLOW_RUNS: 'ci:getWorkflowRuns',
  CI_GET_ACTIVE_RUNS: 'ci:getActiveRuns',
  CI_GET_RUN_JOBS: 'ci:getRunJobs',
  CI_CANCEL_RUN: 'ci:cancelRun',
  CI_GET_JOB_LOG: 'ci:getJobLog',
  CI_SAVE_JOB_LOG: 'ci:saveJobLog',
  CI_START_POLLING: 'ci:startPolling',
  CI_STOP_POLLING: 'ci:stopPolling',
  CI_FIX_WITH_CLAUDE: 'ci:fixWithClaude',
  CI_RERUN_FAILED: 'ci:rerunFailed',
  CI_DISPATCH_WORKFLOW: 'ci:dispatchWorkflow',
  CI_NAVIGATE_TO_RUN: 'ci:navigateToRun',

  // Pull Requests / Merge Requests
  PR_CHECK_AVAILABLE: 'pr:checkAvailable',
  PR_GET_SETUP_STATUS: 'pr:getSetupStatus',
  PR_RUN_SETUP_ACTION: 'pr:runSetupAction',
  PR_LIST: 'pr:list',
  PR_GET: 'pr:get',
  PR_CREATE: 'pr:create',
  PR_GET_DEFAULT_BRANCH: 'pr:getDefaultBranch',
  PR_GET_NEW_URL: 'pr:getNewUrl',

  // Issues
  ISSUE_CHECK_AVAILABLE: 'issue:checkAvailable',
  ISSUE_GET_SETUP_STATUS: 'issue:getSetupStatus',
  ISSUE_RUN_SETUP_ACTION: 'issue:runSetupAction',
  ISSUE_LIST: 'issue:list',
  ISSUE_GET: 'issue:get',
  ISSUE_CREATE: 'issue:create',
  ISSUE_UPDATE: 'issue:update',
  ISSUE_SET_STATE: 'issue:setState',
  ISSUE_ADD_LABEL: 'issue:addLabel',
  ISSUE_REMOVE_LABEL: 'issue:removeLabel',
  ISSUE_LIST_LABELS: 'issue:listLabels',
  ISSUE_ADD_ASSIGNEE: 'issue:addAssignee',
  ISSUE_REMOVE_ASSIGNEE: 'issue:removeAssignee',
  ISSUE_LIST_ASSIGNEES: 'issue:listAssignees',
  ISSUE_LIST_MILESTONES: 'issue:listMilestones',
  ISSUE_SET_MILESTONE: 'issue:setMilestone',
  ISSUE_LIST_COMMENTS: 'issue:listComments',
  ISSUE_ADD_COMMENT: 'issue:addComment',
  ISSUE_UPDATE_COMMENT: 'issue:updateComment',
  ISSUE_DELETE_COMMENT: 'issue:deleteComment',
  ISSUE_GET_CURRENT_USER: 'issue:getCurrentUser',
  ISSUE_FIX_WITH_CLAUDE: 'issue:fixWithClaude',
  ISSUE_START_POLLING: 'issue:startPolling',
  ISSUE_STOP_POLLING: 'issue:stopPolling',
  ISSUE_GET_TYPE_PROFILES: 'issue:getTypeProfiles',
  ISSUE_SET_TYPE_PROFILES: 'issue:setTypeProfiles',

  // Claude Tasks
  CLAUDE_SEND_TASK: 'claude:sendTask',

  // Plugin windows
  PLUGIN_GET_OPEN_WINDOWS: 'plugin:getOpenWindows',

  // Plugin Update System
  PLUGIN_UPDATE_CHECK: 'pluginUpdate:check',
  PLUGIN_UPDATE_GET_AVAILABLE: 'pluginUpdate:getAvailable',
  PLUGIN_UPDATE_INSTALL: 'pluginUpdate:install',
  PLUGIN_UPDATE_INSTALL_ALL: 'pluginUpdate:installAll',
  PLUGIN_UPDATE_DISMISS: 'pluginUpdate:dismiss',
  PLUGIN_UPDATE_GET_NEW_OVERRIDES: 'pluginUpdate:getNewOverrides',
  PLUGIN_UPDATE_MARK_OVERRIDE_SEEN: 'pluginUpdate:markOverrideSeen',

  // Cloud Integration
  CLOUD_OPEN: 'cloud:open',
  CLOUD_GET_PROVIDERS: 'cloud:getProviders',
  CLOUD_GET_ACTIVE_PROVIDER: 'cloud:getActiveProvider',
  CLOUD_SET_PROVIDER: 'cloud:setProvider',
  CLOUD_GET_DASHBOARD: 'cloud:getDashboard',
  CLOUD_GET_CLUSTERS: 'cloud:getClusters',
  CLOUD_GET_CLUSTER_DETAIL: 'cloud:getClusterDetail',
  CLOUD_GET_WORKLOADS: 'cloud:getWorkloads',
  CLOUD_GET_WORKLOAD_DETAIL: 'cloud:getWorkloadDetail',
  CLOUD_GET_CONSOLE_URL: 'cloud:getConsoleUrl',
  CLOUD_CHECK_AUTH: 'cloud:checkAuth',
  CLOUD_REAUTH: 'cloud:reauth',
  CLOUD_GET_SETUP_STATUS: 'cloud:getSetupStatus',

  // Telemetry
  TELEMETRY_SET_CONSENT: 'telemetry:setConsent',
  TELEMETRY_RECORD_FEATURE: 'telemetry:recordFeature',

  // Usage / Anthropic API
  USAGE_FETCH: 'usage:fetch',
  USAGE_CACHED: 'usage:cached',
  USAGE_SET_KEY: 'usage:setKey',
  USAGE_HAS_KEY: 'usage:hasKey',
  USAGE_CLEAR_KEY: 'usage:clearKey',

  // Main -> Renderer (send)
  PLUGIN_UPDATE_PROGRESS: 'pluginUpdate:progress',
  PLUGIN_UPDATE_STATE_CHANGED: 'pluginUpdate:stateChanged',
  TERMINAL_DATA: 'terminal:data',
  TERMINAL_EXIT: 'terminal:exit',
  SETTINGS_CHANGED: 'settings:changed',
  UPDATER_PROGRESS: 'updater:progress',
  NOTIFICATION_SHOW: 'notification:show',
  PLUGIN_WINDOW_STATE: 'plugin:windowState',

  // Workspace Viewer
  WORKSPACE_READ_DIR: 'workspace:readDir',
  WORKSPACE_READ_TREE: 'workspace:readTree',
  WORKSPACE_OPEN_FILE: 'workspace:openFile',
  WORKSPACE_OPEN_IN_EXPLORER: 'workspace:openInExplorer',
  WORKSPACE_RENAME: 'workspace:rename',
  WORKSPACE_DELETE: 'workspace:delete',
  WORKSPACE_CREATE_FILE: 'workspace:createFile',
  WORKSPACE_CREATE_FOLDER: 'workspace:createFolder',
  WORKSPACE_MOVE_CLAUDE: 'workspace:moveClaude',
  WORKSPACE_DETACH_EDITOR: 'workspace:detachEditor',
  WORKSPACE_SEARCH: 'workspace:search',
  WORKSPACE_REPLACE: 'workspace:replace',
  WORKSPACE_WATCH_START: 'workspace:watchStart',
  WORKSPACE_WATCH_STOP: 'workspace:watchStop',
  WORKSPACE_SCAN_TS_FILES: 'workspace:scanTsFiles',
  WORKSPACE_BUILD_SYMBOL_INDEX: 'workspace:buildSymbolIndex',
  WORKSPACE_QUERY_SYMBOL: 'workspace:querySymbol',
  WORKSPACE_UNDO_REPLACE: 'workspace:undoReplace',
  WORKSPACE_REDO_REPLACE: 'workspace:redoReplace',
  WORKSPACE_READ_FILE: 'workspace:readFile',
  WORKSPACE_WRITE_FILE: 'workspace:writeFile',

  // Memory Plugin
  MEMORY_OPEN: 'memory:open',
  MEMORY_GET_ADAPTERS: 'memory:getAdapters',
  MEMORY_SET_ADAPTER_ENABLED: 'memory:setAdapterEnabled',
  MEMORY_GET_DASHBOARD: 'memory:getDashboard',
  MEMORY_GET_PROJECTS: 'memory:getProjects',
  MEMORY_GET_SESSIONS: 'memory:getSessions',
  MEMORY_GET_SESSION: 'memory:getSession',
  MEMORY_GET_BRANCHES: 'memory:getBranches',
  MEMORY_GET_BRANCH: 'memory:getBranch',
  MEMORY_GET_MESSAGES: 'memory:getMessages',
  MEMORY_GET_TOKEN_SNAPSHOTS: 'memory:getTokenSnapshots',
  MEMORY_GET_IMPORT_LOG: 'memory:getImportLog',
  MEMORY_SEARCH: 'memory:search',
  MEMORY_GET_CONTEXT_SUMMARY: 'memory:getContextSummary',
  MEMORY_GET_DB_INFO: 'memory:getDbInfo',
  MEMORY_REFRESH: 'memory:refresh',
  MEMORY_INSTALL_ADAPTER: 'memory:installAdapter',
  MEMORY_UNINSTALL_ADAPTER: 'memory:uninstallAdapter',
  MEMORY_GET_ADAPTER_CONFIG: 'memory:getAdapterConfig',
  MEMORY_SET_ADAPTER_CONFIG: 'memory:setAdapterConfig',
  MEMORY_RUN_MAINTENANCE: 'memory:runMaintenance',

  // Test Runner
  TEST_RUNNER_OPEN: 'testRunner:open',
  TEST_RUNNER_DETECT: 'testRunner:detect',
  TEST_RUNNER_DISCOVER: 'testRunner:discover',
  TEST_RUNNER_RUN: 'testRunner:run',
  TEST_RUNNER_STOP: 'testRunner:stop',
  TEST_RUNNER_GET_STATUS: 'testRunner:getStatus'
} as const
