export const IPC = {
  // Renderer -> Main (invoke/handle)
  TERMINAL_SPAWN: 'terminal:spawn',
  TERMINAL_WRITE: 'terminal:write',
  TERMINAL_RESIZE: 'terminal:resize',
  TERMINAL_KILL: 'terminal:kill',
  TERMINAL_GET_SESSION_ID: 'terminal:getSessionId',
  TERMINAL_SYNC_ORDER: 'terminal:syncOrder',
  DOCK_GET_INFO: 'dock:getInfo',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  APP_NEW_DOCK: 'app:newDock',
  APP_PICK_DIRECTORY: 'app:pickDirectory',
  APP_GET_RECENT_PATHS: 'app:getRecentPaths',
  APP_REMOVE_RECENT_PATH: 'app:removeRecentPath',
  APP_OPEN_DOCK_PATH: 'app:openDockPath',
  WIN_MINIMIZE: 'win:minimize',
  WIN_MAXIMIZE: 'win:maximize',
  WIN_CLOSE: 'win:close',
  APP_OPEN_EXTERNAL: 'app:openExternal',
  APP_OPEN_IN_EXPLORER: 'app:openInExplorer',
  UPDATER_CHECK: 'updater:check',
  UPDATER_DOWNLOAD: 'updater:download',
  UPDATER_INSTALL: 'updater:install',
  GIT_CHECK: 'git:check',
  GIT_INSTALL: 'git:install',
  CLAUDE_CHECK_INSTALL: 'claude:checkInstall',
  CLAUDE_INSTALL: 'claude:install',
  CLAUDE_VERSION: 'claude:version',
  DOCK_RESTART: 'dock:restart',
  LINKED_CHECK_MCP: 'linked:checkMcp',
  LINKED_INSTALL_MCP: 'linked:installMcp',
  LINKED_UNINSTALL_MCP: 'linked:uninstallMcp',
  LINKED_SET_ENABLED: 'linked:setEnabled',
  DEBUG_WRITE: 'debug:write',
  DEBUG_OPEN_DEVTOOLS: 'debug:openDevTools',
  DEBUG_OPEN_LOGS: 'debug:openLogs',

  // Main -> Renderer (send)
  TERMINAL_DATA: 'terminal:data',
  TERMINAL_EXIT: 'terminal:exit',
  SETTINGS_CHANGED: 'settings:changed',
  UPDATER_PROGRESS: 'updater:progress'
} as const
